<?php

namespace N9Bundle\Repository;

/**
 * CreationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
