<?php

namespace N9Bundle\Repository;

/**
 * EducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEducationsWithSchool()
    {
        $qb = $this->createQueryBuilder('educ');

        $qb
            ->select('educ')
            ->innerJoin('educ.school', 'sch')
            ->addSelect('sch')
            ->orderBy('educ.year', 'DESC');

        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult();
    }
}
