<?php

namespace N9Bundle\Repository;

/**
 * PhotoTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
