<?php

namespace N9Bundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSkillsByType()
    {
        $qb = $this->createQueryBuilder('skl');

        $qb
            ->select('skl')
            ->innerJoin('skl.skillType', 'type')
            ->addSelect('type')
            ->orderBy('skl.position', 'ASC');
        
        $result = $qb
            ->getQuery()
            ->getResult();

        $listing = array();
        foreach ($result as $skill) {
            $listing[$skill->getSkillType()->getLabel()][] = $skill;
        }
        
        return $listing;
    }
}
