<?php

namespace N9Bundle\Repository;

/**
 * SkillTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
